apiVersion: batch/v1
kind: Job
metadata:
  name: cuda-vector-add
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: cuda-vectoradd
        image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2"
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
      runtimeClassName: nvidia
